### ISSUE TITLE
Improve light mode text contrast for inline code

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#267]
I've hovered over `Crate` in both screenshots.

In light mode the contrast is not good:

<img width="693" alt="image" src="https://github.com/ratatui-org/website/assets/1813121/2ec6dfa9-0025-4c77-9a0c-bfc371611895">

In dark mode it seems fine:

<img width="699" alt="image" src="https://github.com/ratatui-org/website/assets/1813121/598000f4-6970-49aa-b959-dc3f5c72ecb8">

There are some extensions for Firefox (and Chrome) that can catch text contrast issues. Here's a screenshot of Axe Dev Tools:

<img width="1512" alt="image" src="https://github.com/ratatui-org/website/assets/1813121/41bcd3cc-3ffa-4ec9-82cd-d8d53714af10">

**Comment by kdheepak** [comment]
Alternatively, we can move the links into the body of each section.

**Comment by joshka** [comment]
I wanted to use up as little vertical space for the links as possible so that the visual weight is on the widget name and the image to make scrolling while looking for something be the general mode of using the page, so I'd prefer to keep the badges on the title. Probably in light mode hover should go white instead of black, or maybe instead have not change for hover.
