### ISSUE TITLE
Is `impl Widget` introduced in tutorials too early?

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#519]
The tutorials introduce `impl Widget for &App` in the counter tutorials and I'm wondering if too much? A lot of tui-rs + ratatui applications don't implement widgets at all and I think we could introduce that first as a easy to use method of writing tuis. 

I think more complex applications should use `Widget` and `StatefulWidget` traits so it could introduce those in a later tutorial.

**Comment by joshka** [comment]
IMO, most apps (even simple ones) should use the widget approach to drawing a UI. This effectively promotes the idea that the UI is just a composition of parts, and that the built-in widgets are no different to ones you create yourself. This tends to avoid the spaghetti code I've seen in a bunch of apps that use frame directly.

The ideal on this IMO would be to get to a point where WidgetRef is the main abstraction (with WidgetMut being available too) - though perhaps these should be `Render`, `RenderMut`, `RenderWithState` or something (spitballing here).

**Comment by kdheepak** [comment]
I agree that the widgets are a better way to structure apps but if we promote the widget approach, we should probably introduce traits and the `Widget` trait more gently. I know when I first started using Rust, I didn't use any traits and I expect most beginners to Rust that are interested in tutorials will feel similarly. 

My idea for doing this would be to write the counter tutorial without a `Widget` trait and then rewrite it with the `Widget` trait. But I'm open to suggestions for this.

**Comment by joshka** [comment]
I'm very much against the idea of not implementing `Widget` in the tutorial as it leads to generally difficult to follow spaghetti code in user apps (I've read a few and seen this happen - will share some privately so as not to publicly criticize them). The UI as a function in `ui.rs` is a _module as a junk draw_ approach to organization, as it horizontally partitions the code that displays state from the code that maintains that state. I feel generally that horizontal organization is an anti-pattern in any system no matter how simple. I've worked on a lot of systems, some vertical sliced, some horizontal, and the vertical sliced systems were generally easier to navigate and maintain. I want to generally introduce practices that avoid horizontal organization right from the start. `impl Widget for T` does this nicely, while avoiding it does the opposite.

I don't like the approach of introducing an anti-pattern in docs and then later fixing it / changing it with more docs. It suffers from an assumption that users will read all the docs (and not just the first doc). It also leads to an inherently linear path through the docs instead one which allows users to read the docs that are relevant to their problem.

The hello world tutorial has a `Widget`-free implementation. I don't think it's necessary to do this in the counter app too.

Traits are introduced in the rust book before:

- lifetimes
- tests
- command line apps
- iterators and closures
- publishing to <crates.io>

All of these are things that app writers will want to generally use in their apps, so I don't think it's unreasonable to just use Widgets as the organizational concept from the beginning. There's a good quote from the [method implementation page](https://doc.rust-lang.org/book/ch05-03-method-syntax.html) in the book that applies as much to struct impl blocks as to trait impl blocks.

> The main reason for using methods instead of functions, in addition to providing method syntax and not having to repeat the type of self in every method’s signature, is for organization. We’ve put all the things we can do with an instance of a type in one impl block rather than making future users of our code search for capabilities of Rectangle in various places in the library we provide.

---

> I know when I first started using Rust, I didn't use any traits.

You likely didn't implement any immediately, but you probably saw a bunch of docs on traits that are implemented by things (Specifically you would have seen the `Display` and `Debug` traits pretty early on. `Widget` is less difficult than those).

I would encourage instead adding a feedback form to the tutorials to solicit actual user pain points (and then thinking about that feedback in aggregate rather than over-indexing on a specific user). We might get some more info on level of knowledge / problems / unclear wording / etc.

> We should probably introduce traits and the `Widget` trait more gently.

I'm in somewhat agreement here that the introduction of widgets could be rewritten, but bear in mind that tutorials are not a place to teach theory, but more a place to show how to do the tasks. From https://diataxis.fr/tutorials/ (The entire article is worth a read but here are a few relevant snippets):

> The first rule of teaching is simply: **don’t try to teach**. Your job, as a teacher, is to provide the learner with an experience that will allow them to learn. A teacher inevitably feels a kind of anxiety to impart knowledge and understanding, but if you give into it and try to teach by telling and explaining, you will jeopardise the learning experience.

> Instead, _allow learning to take place_, and trust that it will. Give your learner things to _do_, through which they can learn. Only your pupil can learn. Sadly, however much you desire it, you will not be able to learn for your pupil. You cannot make them learn. All you can do is make it so they can learn.

> _A tutorial is not the place for explanation_. In a tutorial, the user is focused on correctly following your directions and getting the expected results. Later, when they are ready, they will seek explanation, but right now they are concerned with doing. Explanation distracts their attention from that, and blocks their learning.

I know we've talked a bit about how much to adhere to the diataxis guidance, but I think this entire article is fairly reasonable, and has a lot of advice that would be difficult to refute.

---

Here's the current text where we introduce the `Widget` trait:

> Every application needs to render the state to the screen by calling Terminal::draw() with a closure that accepts a Frame. The application will call methods on the Frame to render the state of the application (and update the cursor if needed).

> In the interests of composability, it can be convenient to implement the Widget trait on your app type instead of directly calling methods on frame.

> First, add a new impl Widget for &App block. The render function will create a block with a title, instruction text on the bottom, and some borders. Render a Paragraph widget with the application’s state (the value of the Apps counter field) inside the block. The block and paragraph will take up the entire size of the widget:

I think there's some scope room for rewriting this in a way that is bit more task focused while still giving some rationale, but I'd suggest keeping it to approximately the same level of detail we have here. So perhaps something like:

> To render the UI, an application calls`Terminal::draw()` with a closure that accepts a `Frame`. The most important method on `Frame` is `render_widget()` which renders any type that implements the `Widget` trait (link "widget trait" to a new concepts/widgets article perhaps) such as `Paragraph`, `List` etc., We will implement the `Widget` for the `App` struct so that the code related to rendering is organized in a single place. This allows us to call `Frame::render_widget()` with the app in the closure passed to `Terminal::draw`.

> First, add a new `impl Widget for &App` block. We implement this on a reference to the App type, as the render function will not mutate any state, and we want to be able to use the app after the call to draw. In the render function, ...

**Comment by kdheepak** [comment]
Thanks for writing out such a detailed and thoughtful response. I think your comment has convinced me that the counter tutorial should introduce using the `Widget` trait and doesn't need a previous section that does it without the `Widget` trait. The order in which concepts are introduced in the rust book is a great metric. 

I think I'm fine with the text you share about the level of detail in the tutorial.

I do think we need more information elsewhere in the website then instead. Understanding why the `Widget` trait works requires understanding that:

1) when calling `frame.render_widget(Object, frame.size())`, `Object` implements the `Widget` trait
2) `Object.render(area, buf)` is passed a `buf` where `buf` is one of the two buffers in the double buffer implementation 

Currently this is only mentioned in "Under the hood" in rendering, and we should link to the relevant section for this.

**Comment by kdheepak** [comment]
Maybe I should rename the issue to ```Should `Widget` trait be explained in more detail in a separate section?```?

**Comment by joshka** [comment]
I'm fine with just adding a couple of todos to this:
- [x] Add a concepts/widgets article
- [x] Update the language introducing widgets in the counter tutorial from https://github.com/ratatui-org/ratatui-website/issues/519#issuecomment-2015043962 and link to the concepts article
